(() => {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const runtime = (() => { try { return JSON.parse($("cpa-plugin-runtime-config").textContent || "{}"); } catch (_) { return {}; } })();
  const state = { providers: [], credentials: [], settings: {}, busy: false, statePollTimer: null };
  const CPA_SOURCES = [
    { endpoint: "/v0/management/openai-compatibility", root: "openai-compatibility", label: "OpenAI 兼容", openai: true },
    { endpoint: "/v0/management/claude-api-key", root: "claude-api-key", label: "Claude" },
    { endpoint: "/v0/management/codex-api-key", root: "codex-api-key", label: "Codex" },
    { endpoint: "/v0/management/gemini-api-key", root: "gemini-api-key", label: "Gemini" },
    { endpoint: "/v0/management/interactions-api-key", root: "interactions-api-key", label: "Interactions" },
    { endpoint: "/v0/management/xai-api-key", root: "xai-api-key", label: "xAI" },
    { endpoint: "/v0/management/vertex-api-key", root: "vertex-api-key", label: "Vertex" }
  ];
  const hostStorage = () => { try { return window.parent !== window ? window.parent.localStorage : localStorage; } catch (_) { return null; } };
  function decode(value) { const prefix = "enc::v1::"; if (typeof value !== "string" || !value.startsWith(prefix)) return value; try { const raw = atob(value.slice(prefix.length)), key = new TextEncoder().encode(`cli-proxy-api-webui::secure-storage|${location.host}|${navigator.userAgent}`); return new TextDecoder().decode(Uint8Array.from(raw, (c, i) => c.charCodeAt(0) ^ key[i % key.length])); } catch (_) { return value; } }
  function api() { const storage = hostStorage(); if (!storage) return null; try { const read = (name) => { const raw = storage.getItem(name); if (!raw) return null; const text = decode(raw); try { return JSON.parse(text); } catch (_) { return text; } }; const auth = read("cli-proxy-auth") || {}, value = auth.state || auth; const base = String(value.apiBase || read("apiBase") || location.origin).replace(/\/+$/, ""); const key = String(value.managementKey || read("managementKey") || "").trim(); return base && key ? { base, key } : null; } catch (_) { return null; } }
  async function request(path, options = {}) { const current = api(); if (!current) throw new Error("未找到 CPA 管理会话，请从 CPA 管理中心打开插件。"); const response = await fetch(current.base + path, { method: options.method || "GET", cache: "no-store", headers: { Accept: "application/json", Authorization: `Bearer ${current.key}`, ...(options.body ? { "Content-Type": "application/json" } : {}) }, ...(options.body ? { body: options.body } : {}) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || payload.message || payload.status?.message || `请求失败（HTTP ${response.status}）`); return payload; }
  const esc = (value) => String(value ?? "").replace(/[&<>\'"]/g, (c) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[c]);
  const num = (value, digits = 2) => value === null || value === undefined || Number.isNaN(Number(value)) ? "-" : new Intl.NumberFormat("zh-CN", { maximumFractionDigits: digits }).format(Number(value));
  const money = (value, unit = "USD") => value === null || value === undefined ? "-" : `${num(value, 4)} ${unit}`;
  const date = (value) => { const d = new Date(value); return value && !Number.isNaN(d.getTime()) ? d.toLocaleString("zh-CN", { hour12: false }) : "-"; };
  function message(text, error = false) { const node = $("notice"); node.textContent = text || ""; node.className = text ? `notice${error ? " error" : ""}` : "notice hidden"; }
  function busy(value) { state.busy = value; [$('reloadBtn'), $('refreshAllBtn')].forEach((node) => { if (node) node.disabled = value; }); $('reloadBtn').textContent = value ? '读取中…' : '重新读取 CPA'; $('refreshAllBtn').textContent = value ? '同步中…' : '同步数据'; }
  function scheduleStatePolling() { if (state.statePollTimer) clearInterval(state.statePollTimer); const minutes = Math.max(1, Number(state.settings?.refresh_interval_minutes) || 1); state.statePollTimer = setInterval(() => { if (!state.busy) loadState(); }, minutes * 60 * 1000); }
  function normalizeSource(source, raw) {
    if (!Array.isArray(raw)) return [];
    const result = [];
    if (source.openai) {
      raw.forEach((item, providerIndex) => { const baseURL = String(item["base-url"] || "").trim(); let entries = Array.isArray(item["api-key-entries"]) ? item["api-key-entries"] : []; if (!entries.length && Array.isArray(item["api-keys"])) entries = item["api-keys"].map((key) => ({ "api-key": key })); entries.forEach((entry, keyIndex) => { const apiKey = String(entry["api-key"] || "").trim(); if (!baseURL || !apiKey) return; const sourceRef = String(entry["auth-index"] || `${providerIndex}:${keyIndex}:${baseURL}:${apiKey.slice(-4)}`); result.push({ auth_index: sourceRef, source_ref: sourceRef, source_type: "sub2api", name: String(item.name || `OpenAI 兼容 ${providerIndex + 1}`) + (entries.length > 1 ? ` #${keyIndex + 1}` : ""), provider: source.label, base_url: baseURL, api_key: apiKey }); }); });
      return result;
    }
    raw.forEach((item, index) => { const baseURL = String(item["base-url"] || "").trim(); const apiKey = String(item["api-key"] || "").trim(); if (!baseURL || !apiKey) return; const sourceRef = String(item["auth-index"] || `${index}:${baseURL}:${apiKey.slice(-4)}`); result.push({ auth_index: sourceRef, source_ref: sourceRef, source_type: "sub2api", name: item.prefix ? `${source.label} · ${item.prefix}` : `${source.label} ${index + 1}`, provider: source.label, base_url: baseURL, api_key: apiKey }); });
    return result;
  }
  async function loadCandidates() {
    const saved = new Map(state.providers.map((provider) => [provider.source_ref, provider]));
    const results = await Promise.allSettled(CPA_SOURCES.map(async (source) => normalizeSource(source, (await request(source.endpoint))[source.root])));
    state.credentials = results.flatMap((result) => result.status === "fulfilled" ? result.value : []);
    state.credentials.forEach((candidate) => { const provider = saved.get(candidate.source_ref); if (provider) { candidate.provider_id = provider.id; candidate.saved = provider; } });
  }
  function providerCard(p, credentialOnly = false) { const s=p.latest||{}, u=s.usage||{}, b=s.billing||{}; const multiplier=b.rate_multiplier==null?"-":`${num(b.rate_multiplier,4)}×`; const action=credentialOnly?`data-credential-id="${esc(p.auth_index)}"`:`data-provider-id="${esc(p.id)}"`; return `<article class="provider-card ${credentialOnly?"is-unconfigured":""}"><header><div><h2>${esc(p.name)}</h2><p>${esc(p.source_type)} · ${esc(p.base_url)}</p></div><button class="button outline settings-button" ${action} type="button">设置</button></header>${credentialOnly?`<div class="unconfigured-note">来自 CPA，尚未启用监控</div>`:`<div class="card-balance"><span>余额</span><strong>${money(u.balance,s.unit)}</strong><span class="card-updated">更新时间：${esc(date(s.observed_at))}</span></div><div class="card-metrics"><div><span>组倍率</span><b>${multiplier}</b></div><div><span>今日总 Token</span><b>${num(u.today_tokens,0)}</b></div><div><span>今日请求数</span><b>${num(u.today_requests,0)}</b></div><div><span>今日实际费用</span><b>${money(u.today_actual_cost,s.unit)}</b></div></div>`}</article>`; }
  function renderSupplierList() { const filter=$("providerFilter").value.trim().toLowerCase(); const providers=state.providers.filter((p)=>`${p.name} ${p.source_type} ${p.base_url}`.toLowerCase().includes(filter)); const saved=new Set(state.providers.map((p)=>p.source_ref)); const pending=state.credentials.filter((c)=>!saved.has(c.source_ref)&&`${c.name} ${c.source_type} ${c.base_url}`.toLowerCase().includes(filter)); const items=[...providers.map((p)=>({item:p,pending:false})),...pending.map((p)=>({item:p,pending:true}))].sort((a,b)=>String(a.item.source_ref||"").localeCompare(String(b.item.source_ref||""))); $("supplierCount").textContent=items.length; $("supplierList").innerHTML=items.map(({item,pending})=>providerCard(item,pending)).join("")||`<div class="supplier-none">CPA 中暂无可用供应商</div>`; }
  function renderDetail() { renderSupplierList(); }
  async function loadState() { busy(true); try { const payload = await request(runtime.StatePath); state.providers = Array.isArray(payload.providers) ? payload.providers : []; state.settings = payload.settings || {}; scheduleStatePolling(); $("monitorSubtitle").textContent = `${state.providers.length} 个供应商已纳入监控`; $("refreshStatus").textContent = state.providers.length ? `最近刷新：${date(state.providers.map((p) => p.latest?.observed_at).filter(Boolean).sort().at(-1))}` : "未刷新"; renderDetail(); if (payload.status?.configured === false) message(payload.status.message || "插件尚未配置。", true); else message(""); } catch (error) { message(error.message, true); } finally { busy(false); } }
  async function refresh(ids) { busy(true); try { await request(runtime.RefreshPath, { method:"POST", body:JSON.stringify({ provider_ids:ids}) }); await loadState(); } catch (error) { message(error.message,true); busy(false); } }
  function openCredential(authIndex) { const c = state.credentials.find((item) => (item.auth_index || item.source_ref) === authIndex); if (!c) return; const provider = state.providers.find((item) => item.id === c.provider_id); $("providerForm").reset(); $("authIndex").value = c.auth_index || c.source_ref; $("providerId").value = provider?.id || ""; $("credentialName").value = c.name; $("providerName").value = provider?.name || c.name; $("baseURL").value = provider?.base_url || c.base_url || ""; $("sourceType").value = provider?.source_type || c.source_type || "sub2api"; $("sourceType").disabled = Boolean(provider); $("enabled").checked = true; $("providerDialogTitle").textContent = provider ? "编辑监控配置" : "配置并启用"; $("formError").textContent = ""; toggleNewAPI(); $("providerDialog").showModal(); }
  function toggleNewAPI() { $("newAPICredentials").classList.toggle("hidden", $("sourceType").value !== "new-api"); }
  async function saveProvider(event) { event.preventDefault(); const candidate = state.credentials.find((item) => (item.auth_index || item.source_ref) === $("authIndex").value); const payload = { id:$('providerId').value, auth_index:$('authIndex').value, enabled:$('enabled').checked, source_type:$('sourceType').value, name:$('providerName').value.trim(), base_url:$('baseURL').value.trim(), api_key:candidate?.api_key || '', new_api_user:$('newAPIUser').value.trim(), new_api_authorization:$('newAPIAuthorization').value.trim() }; try { await request(runtime.ProvidersPath,{method:'POST',body:JSON.stringify(payload)}); $('providerDialog').close(); message('监控配置已保存。'); await loadState(); await loadCandidates(); } catch(error) { $('formError').textContent = error.message; } }
  $("reloadBtn").addEventListener("click", async () => { await loadState(); await loadCandidates(); }); $("refreshAllBtn").addEventListener("click", () => refresh([])); $("providerFilter").addEventListener("input", renderSupplierList); $("supplierList").addEventListener("click", (event) => { const button = event.target.closest("[data-provider-id],[data-credential-id]"); if (!button) return; if (button.dataset.credentialId) openCredential(button.dataset.credentialId); else { const provider=state.providers.find((p)=>p.id===button.dataset.providerId); const credential=state.credentials.find((c)=>c.provider_id===provider?.id); if(credential) openCredential(credential.auth_index); } }); $("sourceType").addEventListener("change", toggleNewAPI); $("providerForm").addEventListener("submit", saveProvider); (async () => { await loadState(); await loadCandidates(); })();
})();
